name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Run workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and test
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/docx-to-pdf .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push your-dockerhub-username/docx-to-pdf

      # Deploy to AWS EC2
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            # Pull the latest image
            docker pull your-dockerhub-username/node-docx-to-pdf
            # Stop the existing container (if running)
            docker stop node-docx-to-pdf || true
            docker rm node-docx-to-pdf || true
            # Run the new container
            docker run -d -p 3001:3001 --name node-docx-to-pdf your-dockerhub-username/node-docx-to-pdf
